// <auto-generated />
using System;
using API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API.Data.Migrations
{
    [DbContext(typeof(MagazineDbContext))]
    [Migration("20220702182839_AddedImageEntityToDb")]
    partial class AddedImageEntityToDb
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.6");

            modelBuilder.Entity("API.Entities.ArticleEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Contents")
                        .IsRequired()
                        .HasMaxLength(3000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Articles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("31c3a76c-e04c-4cd4-a324-40595a1a9a2d"),
                            Contents = "This is content for article 1",
                            Summary = "This is summary for article 1",
                            Title = "Testing bla bla 1"
                        },
                        new
                        {
                            Id = new Guid("30bca8b2-f61c-4125-b71e-9ec62ffc293e"),
                            Contents = "This is content for article 2",
                            Summary = "This is summary for article 2",
                            Title = "Testing bla bla 2"
                        },
                        new
                        {
                            Id = new Guid("f9135489-0aaa-4b64-ab9f-e49107177ac4"),
                            Contents = "This is content for article 3",
                            Summary = "This is summary for article 3",
                            Title = "Testing bla bla 3"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
